### ISSUE TITLE
Kubernetes Template

### ISSUE THREAD

**Issue by madejackson** [ajmandourah/bazarr-sync#3]
Working Kubernetes-Template for my K3s-Cluster, for anyone is interested:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr-sync
  namespace: plex
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: bazarr-sync
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr-sync
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
        - name: bazarr-sync
          image: ghcr.io/ajmandourah/bazarr-sync:latest
          command: ["bazarr-sync"]
          args: ["sync", "shows"]
          volumeMounts:
            - mountPath: /usr/src/app/config.yaml
              subPath: config.yaml
              name: bazarr-sync-config
              readOnly: true
      volumes:
        - name: bazarr-sync-config
          configMap:
            name: bazarr-sync-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarr-sync-config
  namespace: plex
data:
  config.yaml: |-
    #config file example, please don't use quotes
    ###########################
    #
    #Address: the address of your bazarr instance. this can be either an ip address or a url (if you reverse proxy bazarr),
    #this can also be bazarr's container name if you use docker, make sure bazarr-sync instance is in the same network as bazarr and >
    #docker network as name resolution won't happen there.
    Address: bazarr
    #
    #Port: bazarrs port. by default bazarr uses 6767. in case of reverse proxy, you can use 443 or 80 as per your configuration
    Port: 80
    #
    #protocol: this can be http or https
    Protocol: http
    #
    #ApiToken: you can get this from bazarr setting>general . no quotes needed.
    ApiToken: <redacted>
```
